from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon, QFont, QFontDatabase


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 584)
        MainWindow.setWindowIcon(QIcon('resources/cxk_icon.ico'))
        fontDb = QFontDatabase()
        fontID = fontDb.addApplicationFont(":resources/resources/hk4e_zh-cn.ttf")
        fontDb.applicationFontFamilies(fontID)
        font = QFont('HYWenHei-85W')
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(80, 10, 481, 23))
        self.progressBar.setStyleSheet("QProgressBar {border: 2px solid grey; border-radius: 5px; background-color: #FFFFFF; text-align:center; font-size:20px}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.hide()
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 611, 551))
        self.tabWidget.setStyleSheet("background:url(:/resources/resources/cxk.png);")
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Page1 = QtWidgets.QWidget()
        self.Page1.setObjectName("Page1")
        self.pushButton_1 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_1.setGeometry(QtCore.QRect(140, 10, 61, 51))
        self.pushButton_1.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_5 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 10, 141, 51))
        self.pushButton_5.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 10, 61, 51))
        self.pushButton_2.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 10, 61, 51))
        self.pushButton_3.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 10, 61, 51))
        self.pushButton_4.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 130, 61, 51))
        self.pushButton_9.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 130, 61, 51))
        self.pushButton_10.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_11.setGeometry(QtCore.QRect(160, 130, 61, 51))
        self.pushButton_11.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_6 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 70, 151, 51))
        self.pushButton_6.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_12 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_12.setGeometry(QtCore.QRect(230, 130, 81, 51))
        self.pushButton_12.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_13.setGeometry(QtCore.QRect(320, 130, 61, 51))
        self.pushButton_13.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_7 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_7.setGeometry(QtCore.QRect(300, 70, 131, 51))
        self.pushButton_7.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_8.setGeometry(QtCore.QRect(440, 70, 81, 51))
        self.pushButton_8.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_14 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_14.setGeometry(QtCore.QRect(390, 130, 141, 51))
        self.pushButton_14.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 200, 71, 51))
        self.pushButton_15.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_16.setGeometry(QtCore.QRect(100, 200, 141, 51))
        self.pushButton_16.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_17.setGeometry(QtCore.QRect(250, 200, 71, 51))
        self.pushButton_17.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_19 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_19.setGeometry(QtCore.QRect(480, 200, 101, 51))
        self.pushButton_19.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_18 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_18.setGeometry(QtCore.QRect(330, 200, 141, 51))
        self.pushButton_18.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_20 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_20.setGeometry(QtCore.QRect(20, 260, 71, 51))
        self.pushButton_20.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_21.setGeometry(QtCore.QRect(110, 260, 61, 51))
        self.pushButton_21.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_22.setGeometry(QtCore.QRect(190, 260, 61, 51))
        self.pushButton_22.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_23.setGeometry(QtCore.QRect(270, 260, 71, 51))
        self.pushButton_23.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_24.setGeometry(QtCore.QRect(350, 260, 71, 51))
        self.pushButton_24.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_25.setGeometry(QtCore.QRect(430, 260, 111, 51))
        self.pushButton_25.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_26.setGeometry(QtCore.QRect(20, 320, 131, 51))
        self.pushButton_26.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_27.setGeometry(QtCore.QRect(170, 320, 71, 51))
        self.pushButton_27.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_28.setGeometry(QtCore.QRect(250, 320, 61, 51))
        self.pushButton_28.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_30 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_30.setGeometry(QtCore.QRect(400, 320, 181, 51))
        self.pushButton_30.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_31.setGeometry(QtCore.QRect(20, 380, 91, 51))
        self.pushButton_31.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_32.setGeometry(QtCore.QRect(130, 380, 71, 51))
        self.pushButton_32.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_29 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_29.setGeometry(QtCore.QRect(320, 320, 71, 51))
        self.pushButton_29.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_33 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_33.setGeometry(QtCore.QRect(220, 380, 101, 51))
        self.pushButton_33.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_34.setGeometry(QtCore.QRect(340, 380, 91, 51))
        self.pushButton_34.setStyleSheet("font: 15pt \"HYWenHei-85W\";")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_35.setGeometry(QtCore.QRect(440, 380, 141, 51))
        self.pushButton_35.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_36.setGeometry(QtCore.QRect(20, 450, 81, 51))
        self.pushButton_36.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_37.setGeometry(QtCore.QRect(110, 450, 141, 51))
        self.pushButton_37.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_38.setGeometry(QtCore.QRect(260, 450, 111, 51))
        self.pushButton_38.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_39.setGeometry(QtCore.QRect(380, 450, 91, 51))
        self.pushButton_39.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_40.setGeometry(QtCore.QRect(480, 450, 91, 51))
        self.pushButton_40.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.Page1)
        self.pushButton_41.setGeometry(QtCore.QRect(540, 70, 51, 121))
        self.pushButton_41.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pushButton_41.setObjectName("pushButton_41")
        self.tabWidget.addTab(self.Page1, "")
        self.Page2 = QtWidgets.QWidget()
        self.Page2.setObjectName("Page2")
        self.pushButton_p2_1 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_1.setGeometry(QtCore.QRect(150, 10, 111, 51))
        self.pushButton_p2_1.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_1.setObjectName("pushButton_p2_1")
        self.pushButton_p2_2 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_2.setGeometry(QtCore.QRect(280, 10, 111, 51))
        self.pushButton_p2_2.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_2.setObjectName("pushButton_p2_2")
        self.pushButton_p2_4 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_4.setGeometry(QtCore.QRect(150, 70, 141, 51))
        self.pushButton_p2_4.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p2_4.setObjectName("pushButton_p2_4")
        self.pushButton_p2_3 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_3.setGeometry(QtCore.QRect(410, 10, 111, 51))
        self.pushButton_p2_3.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_3.setObjectName("pushButton_p2_3")
        self.pushButton_p2_5 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_5.setGeometry(QtCore.QRect(310, 70, 131, 51))
        self.pushButton_p2_5.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p2_5.setObjectName("pushButton_p2_5")
        self.pushButton_p2_6 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_6.setGeometry(QtCore.QRect(10, 130, 111, 41))
        self.pushButton_p2_6.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p2_6.setObjectName("pushButton_p2_6")
        self.pushButton_p2_7 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_7.setGeometry(QtCore.QRect(450, 70, 111, 51))
        self.pushButton_p2_7.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_7.setObjectName("pushButton_p2_7")
        self.pushButton_p2_8 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_8.setGeometry(QtCore.QRect(10, 180, 111, 51))
        self.pushButton_p2_8.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_8.setObjectName("pushButton_p2_8")
        self.pushButton_p2_9 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_9.setGeometry(QtCore.QRect(320, 130, 121, 51))
        self.pushButton_p2_9.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_9.setObjectName("pushButton_p2_9")
        self.pushButton_p2_10 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_10.setGeometry(QtCore.QRect(10, 240, 111, 51))
        self.pushButton_p2_10.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_10.setObjectName("pushButton_p2_10")
        self.pushButton_p2_11 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_11.setGeometry(QtCore.QRect(140, 190, 121, 51))
        self.pushButton_p2_11.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_11.setObjectName("pushButton_p2_11")
        self.pushButton_p2_12 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_12.setGeometry(QtCore.QRect(270, 190, 111, 51))
        self.pushButton_p2_12.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_12.setObjectName("pushButton_p2_12")
        self.pushButton_p2_13 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_13.setGeometry(QtCore.QRect(460, 130, 111, 51))
        self.pushButton_p2_13.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_13.setObjectName("pushButton_p2_13")
        self.pushButton_p2_14 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_14.setGeometry(QtCore.QRect(140, 310, 121, 51))
        self.pushButton_p2_14.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_14.setObjectName("pushButton_p2_14")
        self.pushButton_p2_15 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_15.setGeometry(QtCore.QRect(280, 310, 121, 51))
        self.pushButton_p2_15.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_15.setObjectName("pushButton_p2_15")
        self.pushButton_p2_16 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_16.setGeometry(QtCore.QRect(410, 310, 121, 51))
        self.pushButton_p2_16.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_16.setObjectName("pushButton_p2_16")
        self.pushButton_p2_17 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_17.setGeometry(QtCore.QRect(10, 300, 111, 51))
        self.pushButton_p2_17.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_17.setObjectName("pushButton_p2_17")
        self.pushButton_p2_18 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_18.setGeometry(QtCore.QRect(130, 370, 131, 51))
        self.pushButton_p2_18.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_18.setObjectName("pushButton_p2_18")
        self.pushButton_p2_19 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_19.setGeometry(QtCore.QRect(540, 190, 61, 161))
        self.pushButton_p2_19.setStyleSheet("font: 18pt \"HYWenHei-85W\";")
        self.pushButton_p2_19.setObjectName("pushButton_p2_19")
        self.pushButton_p2_20 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_20.setGeometry(QtCore.QRect(10, 370, 111, 51))
        self.pushButton_p2_20.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_20.setObjectName("pushButton_p2_20")
        self.pushButton_p2_21 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_21.setGeometry(QtCore.QRect(150, 130, 151, 51))
        self.pushButton_p2_21.setStyleSheet("font: 18pt \"HYWenHei-85W\";")
        self.pushButton_p2_21.setObjectName("pushButton_p2_21")
        self.pushButton_p2_22 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_22.setGeometry(QtCore.QRect(140, 250, 171, 51))
        self.pushButton_p2_22.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p2_22.setObjectName("pushButton_p2_22")
        self.pushButton_p2_23 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_23.setGeometry(QtCore.QRect(150, 440, 171, 51))
        self.pushButton_p2_23.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_23.setObjectName("pushButton_p2_23")
        self.pushButton_p2_24 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_24.setGeometry(QtCore.QRect(400, 190, 111, 51))
        self.pushButton_p2_24.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_24.setObjectName("pushButton_p2_24")
        self.pushButton_p2_25 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_25.setGeometry(QtCore.QRect(280, 370, 111, 51))
        self.pushButton_p2_25.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_25.setObjectName("pushButton_p2_25")
        self.pushButton_p2_26 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_26.setGeometry(QtCore.QRect(410, 370, 151, 51))
        self.pushButton_p2_26.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_26.setObjectName("pushButton_p2_26")
        self.pushButton_p2_27 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_27.setGeometry(QtCore.QRect(10, 440, 121, 51))
        self.pushButton_p2_27.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_27.setObjectName("pushButton_p2_27")
        self.pushButton_p2_28 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_28.setGeometry(QtCore.QRect(340, 440, 201, 51))
        self.pushButton_p2_28.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p2_28.setObjectName("pushButton_p2_28")
        self.pushButton_p2_29 = QtWidgets.QPushButton(self.Page2)
        self.pushButton_p2_29.setGeometry(QtCore.QRect(320, 250, 171, 51))
        self.pushButton_p2_29.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p2_29.setObjectName("pushButton_p2_29")
        self.tabWidget.addTab(self.Page2, "")
        self.Page3 = QtWidgets.QWidget()
        self.Page3.setObjectName("Page3")
        self.pushButton_p3_1 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_1.setGeometry(QtCore.QRect(150, 30, 131, 51))
        self.pushButton_p3_1.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_1.setObjectName("pushButton_p3_1")
        self.pushButton_p3_2 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_2.setGeometry(QtCore.QRect(300, 30, 131, 51))
        self.pushButton_p3_2.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_2.setObjectName("pushButton_p3_2")
        self.pushButton_p3_3 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_3.setGeometry(QtCore.QRect(450, 30, 131, 51))
        self.pushButton_p3_3.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_3.setObjectName("pushButton_p3_3")
        self.pushButton_p3_4 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_4.setGeometry(QtCore.QRect(150, 90, 131, 41))
        self.pushButton_p3_4.setStyleSheet("font: 12pt \"HYWenHei-85W\";")
        self.pushButton_p3_4.setObjectName("pushButton_p3_4")
        self.pushButton_p3_5 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_5.setGeometry(QtCore.QRect(290, 90, 91, 41))
        self.pushButton_p3_5.setStyleSheet("font: 12pt \"HYWenHei-85W\";")
        self.pushButton_p3_5.setObjectName("pushButton_p3_5")
        self.pushButton_p3_6 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_6.setGeometry(QtCore.QRect(390, 90, 91, 41))
        self.pushButton_p3_6.setStyleSheet("font: 12pt \"HYWenHei-85W\";")
        self.pushButton_p3_6.setObjectName("pushButton_p3_6")
        self.pushButton_p3_7 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_7.setGeometry(QtCore.QRect(490, 90, 101, 41))
        self.pushButton_p3_7.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_7.setObjectName("pushButton_p3_7")
        self.pushButton_p3_8 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_8.setGeometry(QtCore.QRect(20, 140, 121, 41))
        self.pushButton_p3_8.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_8.setObjectName("pushButton_p3_8")
        self.pushButton_p3_9 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_9.setGeometry(QtCore.QRect(150, 140, 91, 41))
        self.pushButton_p3_9.setStyleSheet("font: 12pt \"HYWenHei-85W\";")
        self.pushButton_p3_9.setObjectName("pushButton_p3_9")
        self.pushButton_p3_10 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_10.setGeometry(QtCore.QRect(260, 140, 121, 41))
        self.pushButton_p3_10.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_10.setObjectName("pushButton_p3_10")
        self.pushButton_p3_11 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_11.setGeometry(QtCore.QRect(390, 140, 121, 41))
        self.pushButton_p3_11.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_11.setObjectName("pushButton_p3_11")
        self.pushButton_p3_12 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_12.setGeometry(QtCore.QRect(20, 190, 71, 41))
        self.pushButton_p3_12.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_12.setObjectName("pushButton_p3_12")
        self.pushButton_p3_13 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_13.setGeometry(QtCore.QRect(100, 190, 181, 41))
        self.pushButton_p3_13.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_13.setObjectName("pushButton_p3_13")
        self.pushButton_p3_14 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_14.setGeometry(QtCore.QRect(410, 190, 161, 41))
        self.pushButton_p3_14.setStyleSheet("font: 12pt \"HYWenHei-85W\";")
        self.pushButton_p3_14.setObjectName("pushButton_p3_14")
        self.pushButton_p3_15 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_15.setGeometry(QtCore.QRect(290, 190, 101, 41))
        self.pushButton_p3_15.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_15.setObjectName("pushButton_p3_15")
        self.pushButton_p3_16 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_16.setGeometry(QtCore.QRect(20, 240, 141, 41))
        self.pushButton_p3_16.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_16.setObjectName("pushButton_p3_16")
        self.pushButton_p3_17 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_17.setGeometry(QtCore.QRect(180, 240, 91, 41))
        self.pushButton_p3_17.setStyleSheet("font: 20pt \"HYWenHei-85W\";")
        self.pushButton_p3_17.setObjectName("pushButton_p3_17")
        self.pushButton_p3_18 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_18.setGeometry(QtCore.QRect(290, 240, 201, 41))
        self.pushButton_p3_18.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_18.setObjectName("pushButton_p3_18")
        self.pushButton_p3_19 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_19.setGeometry(QtCore.QRect(10, 350, 91, 41))
        self.pushButton_p3_19.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_19.setObjectName("pushButton_p3_19")
        self.pushButton_p3_20 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_20.setGeometry(QtCore.QRect(130, 350, 91, 41))
        self.pushButton_p3_20.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_20.setObjectName("pushButton_p3_20")
        self.pushButton_p3_21 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_21.setGeometry(QtCore.QRect(250, 350, 91, 41))
        self.pushButton_p3_21.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_21.setObjectName("pushButton_p3_21")
        self.pushButton_p3_22 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_22.setGeometry(QtCore.QRect(370, 350, 91, 41))
        self.pushButton_p3_22.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_22.setObjectName("pushButton_p3_22")
        self.pushButton_p3_23 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_23.setGeometry(QtCore.QRect(490, 350, 91, 41))
        self.pushButton_p3_23.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_23.setObjectName("pushButton_p3_23")
        self.pushButton_p3_24 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_24.setGeometry(QtCore.QRect(10, 400, 91, 41))
        self.pushButton_p3_24.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_24.setObjectName("pushButton_p3_24")
        self.pushButton_p3_25 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_25.setGeometry(QtCore.QRect(480, 400, 101, 41))
        self.pushButton_p3_25.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_25.setObjectName("pushButton_p3_25")
        self.pushButton_p3_26 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_26.setGeometry(QtCore.QRect(130, 400, 91, 41))
        self.pushButton_p3_26.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_26.setObjectName("pushButton_p3_26")
        self.pushButton_p3_27 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_27.setGeometry(QtCore.QRect(250, 400, 91, 41))
        self.pushButton_p3_27.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_27.setObjectName("pushButton_p3_27")
        self.pushButton_p3_28 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_28.setGeometry(QtCore.QRect(370, 400, 91, 41))
        self.pushButton_p3_28.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_28.setObjectName("pushButton_p3_28")
        self.pushButton_p3_29 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_29.setGeometry(QtCore.QRect(10, 450, 101, 41))
        self.pushButton_p3_29.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_29.setObjectName("pushButton_p3_29")
        self.pushButton_p3_30 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_30.setGeometry(QtCore.QRect(120, 450, 101, 41))
        self.pushButton_p3_30.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_30.setObjectName("pushButton_p3_30")
        self.pushButton_p3_31 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_31.setGeometry(QtCore.QRect(240, 450, 101, 41))
        self.pushButton_p3_31.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_31.setObjectName("pushButton_p3_31")
        self.pushButton_p3_32 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_32.setGeometry(QtCore.QRect(360, 450, 101, 41))
        self.pushButton_p3_32.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_32.setObjectName("pushButton_p3_32")
        self.pushButton_p3_33 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_33.setGeometry(QtCore.QRect(30, 290, 231, 41))
        self.pushButton_p3_33.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_33.setObjectName("pushButton_p3_33")
        self.pushButton_p3_34 = QtWidgets.QPushButton(self.Page3)
        self.pushButton_p3_34.setGeometry(QtCore.QRect(290, 290, 201, 41))
        self.pushButton_p3_34.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.pushButton_p3_34.setObjectName("pushButton_p3_34")
        self.tabWidget.addTab(self.Page3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_p4_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_p4_1.setGeometry(QtCore.QRect(140, 10, 181, 61))
        self.pushButton_p4_1.setStyleSheet("font: 24pt \"HYWenHei-85W\";")
        self.pushButton_p4_1.setObjectName("pushButton_p4_1")
        self.pushButton_p4_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_p4_2.setGeometry(QtCore.QRect(340, 10, 221, 61))
        self.pushButton_p4_2.setStyleSheet("font: 24pt \"HYWenHei-85W\";")
        self.pushButton_p4_2.setObjectName("pushButton_p4_2")
        self.pushButton_p4_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_p4_3.setGeometry(QtCore.QRect(140, 90, 181, 61))
        self.pushButton_p4_3.setStyleSheet("font: 24pt \"HYWenHei-85W\";")
        self.pushButton_p4_3.setObjectName("pushButton_p4_3")
        self.pushButton_p4_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_p4_4.setGeometry(QtCore.QRect(340, 90, 181, 61))
        self.pushButton_p4_4.setStyleSheet("font: 24pt \"HYWenHei-85W\";")
        self.pushButton_p4_4.setObjectName("pushButton_p4_4")
        self.pushButton_p4_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_p4_5.setGeometry(QtCore.QRect(320, 170, 221, 61))
        self.pushButton_p4_5.setStyleSheet("font: 24pt \"HYWenHei-85W\";")
        self.pushButton_p4_5.setObjectName("pushButton_p4_5")
        self.pushButton_p4_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_p4_6.setGeometry(QtCore.QRect(140, 170, 151, 61))
        self.pushButton_p4_6.setStyleSheet("font: 24pt \"HYWenHei-85W\";")
        self.pushButton_p4_6.setObjectName("pushButton_p4_6")
        self.tabWidget.addTab(self.tab, "")
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(20, 80, 121, 51))
        self.pauseButton.setStyleSheet("font: 14pt \"HYWenHei-85W\";")
        self.pauseButton.setObjectName("pauseButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(20, 140, 121, 51))
        self.stopButton.setStyleSheet("font: 16pt \"HYWenHei-85W\";")
        self.stopButton.setObjectName("stopButton")
        self.tabWidget.raise_()
        self.progressBar.raise_()
        self.pauseButton.raise_()
        self.stopButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iKun Box"))
        self.pushButton_1.setText(_translate("MainWindow", "鸡"))
        self.pushButton_5.setText(_translate("MainWindow", "鸡你太美_短"))
        self.pushButton_2.setText(_translate("MainWindow", "你"))
        self.pushButton_3.setText(_translate("MainWindow", "太"))
        self.pushButton_4.setText(_translate("MainWindow", "美"))
        self.pushButton_9.setText(_translate("MainWindow", "你"))
        self.pushButton_10.setText(_translate("MainWindow", "干"))
        self.pushButton_11.setText(_translate("MainWindow", "嘛"))
        self.pushButton_6.setText(_translate("MainWindow", "鸡你实在太美"))
        self.pushButton_12.setText(_translate("MainWindow", "哇哈哈"))
        self.pushButton_13.setText(_translate("MainWindow", "哎吆"))
        self.pushButton_7.setText(_translate("MainWindow", "你干嘛哎吆"))
        self.pushButton_8.setText(_translate("MainWindow", "你干嘛"))
        self.pushButton_14.setText(_translate("MainWindow", "你干嘛（倒）"))
        self.pushButton_15.setText(_translate("MainWindow", "鸡叫"))
        self.pushButton_16.setText(_translate("MainWindow", "全民制作人"))
        self.pushButton_17.setText(_translate("MainWindow", "我是"))
        self.pushButton_19.setText(_translate("MainWindow", "蔡徐坤"))
        self.pushButton_18.setText(_translate("MainWindow", "时长两年半"))
        self.pushButton_20.setText(_translate("MainWindow", "喜欢"))
        self.pushButton_21.setText(_translate("MainWindow", "唱"))
        self.pushButton_22.setText(_translate("MainWindow", "跳"))
        self.pushButton_23.setText(_translate("MainWindow", "Rap"))
        self.pushButton_24.setText(_translate("MainWindow", "篮球"))
        self.pushButton_25.setText(_translate("MainWindow", "Music"))
        self.pushButton_26.setText(_translate("MainWindow", "全民full"))
        self.pushButton_27.setText(_translate("MainWindow", "干嘛"))
        self.pushButton_28.setText(_translate("MainWindow", "啊"))
        self.pushButton_30.setText(_translate("MainWindow", "厉不厉害你坤哥"))
        self.pushButton_31.setText(_translate("MainWindow", "英文名"))
        self.pushButton_32.setText(_translate("MainWindow", "Kun"))
        self.pushButton_29.setText(_translate("MainWindow", "哈哈"))
        self.pushButton_33.setText(_translate("MainWindow", "厉不厉害"))
        self.pushButton_34.setText(_translate("MainWindow", "你坤哥"))
        self.pushButton_35.setText(_translate("MainWindow", "个人练习坤"))
        self.pushButton_36.setText(_translate("MainWindow", "笑死"))
        self.pushButton_37.setText(_translate("MainWindow", "我特别厉害"))
        self.pushButton_38.setText(_translate("MainWindow", "特别厉害"))
        self.pushButton_39.setText(_translate("MainWindow", "大家好"))
        self.pushButton_40.setText(_translate("MainWindow", "两年半"))
        self.pushButton_41.setText(_translate("MainWindow", "你\n"
"干\n"
"↑↓\n"
"嘛"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page1), _translate("MainWindow", "经典"))
        self.pushButton_p2_1.setText(_translate("MainWindow", "三国鸡"))
        self.pushButton_p2_2.setText(_translate("MainWindow", "仙剑鸡"))
        self.pushButton_p2_4.setText(_translate("MainWindow", "赛尔鸡_V"))
        self.pushButton_p2_3.setText(_translate("MainWindow", "化鸡飞"))
        self.pushButton_p2_5.setText(_translate("MainWindow", "鸡出没_V"))
        self.pushButton_p2_6.setText(_translate("MainWindow", "卡点鸡"))
        self.pushButton_p2_7.setText(_translate("MainWindow", "印度鸡"))
        self.pushButton_p2_8.setText(_translate("MainWindow", "大悲鸡"))
        self.pushButton_p2_9.setText(_translate("MainWindow", "小母鸡"))
        self.pushButton_p2_10.setText(_translate("MainWindow", "新年鸡"))
        self.pushButton_p2_11.setText(_translate("MainWindow", "新闻鸡"))
        self.pushButton_p2_12.setText(_translate("MainWindow", "果宝鸡"))
        self.pushButton_p2_13.setText(_translate("MainWindow", "欢喜鸡"))
        self.pushButton_p2_14.setText(_translate("MainWindow", "耶耶鸡"))
        self.pushButton_p2_15.setText(_translate("MainWindow", "葫芦鸡"))
        self.pushButton_p2_16.setText(_translate("MainWindow", "青蛙鸡"))
        self.pushButton_p2_17.setText(_translate("MainWindow", "狂放鸡"))
        self.pushButton_p2_18.setText(_translate("MainWindow", "鸡战_V"))
        self.pushButton_p2_19.setText(_translate("MainWindow", "鸡\n"
"你\n"
"太\n"
"美"))
        self.pushButton_p2_20.setText(_translate("MainWindow", "谢谢鸡"))
        self.pushButton_p2_21.setText(_translate("MainWindow", "仙剑鸡_V"))
        self.pushButton_p2_22.setText(_translate("MainWindow", "本草鸡目_V"))
        self.pushButton_p2_23.setText(_translate("MainWindow", "千年鸡_V"))
        self.pushButton_p2_24.setText(_translate("MainWindow", "植物鸡"))
        self.pushButton_p2_25.setText(_translate("MainWindow", "江南鸡"))
        self.pushButton_p2_26.setText(_translate("MainWindow", "落入鸡尘"))
        self.pushButton_p2_27.setText(_translate("MainWindow", "西游鸡"))
        self.pushButton_p2_28.setText(_translate("MainWindow", "终鸡猎手_V"))
        self.pushButton_p2_29.setText(_translate("MainWindow", "骑鸡再现_V"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page2), _translate("MainWindow", "各种鸡"))
        self.pushButton_p3_1.setText(_translate("MainWindow", "告诉你们"))
        self.pushButton_p3_2.setText(_translate("MainWindow", "如果再黑"))
        self.pushButton_p3_3.setText(_translate("MainWindow", "小心我"))
        self.pushButton_p3_4.setText(_translate("MainWindow", "花点money"))
        self.pushButton_p3_5.setText(_translate("MainWindow", "把你们都"))
        self.pushButton_p3_6.setText(_translate("MainWindow", "告上法庭"))
        self.pushButton_p3_7.setText(_translate("MainWindow", "犯法了"))
        self.pushButton_p3_8.setText(_translate("MainWindow", "用他人的"))
        self.pushButton_p3_9.setText(_translate("MainWindow", "照片改成"))
        self.pushButton_p3_10.setText(_translate("MainWindow", "公鸡母鸡"))
        self.pushButton_p3_11.setText(_translate("MainWindow", "还有母猪"))
        self.pushButton_p3_12.setText(_translate("MainWindow", "荔枝"))
        self.pushButton_p3_13.setText(_translate("MainWindow", "你让我拿什么"))
        self.pushButton_p3_14.setText(_translate("MainWindow", "还要我怎么荔枝"))
        self.pushButton_p3_15.setText(_translate("MainWindow", "荔枝啊"))
        self.pushButton_p3_16.setText(_translate("MainWindow", "荔枝（全）"))
        self.pushButton_p3_17.setText(_translate("MainWindow", "连招"))
        self.pushButton_p3_18.setText(_translate("MainWindow", "ikun真情流露"))
        self.pushButton_p3_19.setText(_translate("MainWindow", "语录1"))
        self.pushButton_p3_20.setText(_translate("MainWindow", "语录2"))
        self.pushButton_p3_21.setText(_translate("MainWindow", "语录3"))
        self.pushButton_p3_22.setText(_translate("MainWindow", "语录4"))
        self.pushButton_p3_23.setText(_translate("MainWindow", "语录5"))
        self.pushButton_p3_24.setText(_translate("MainWindow", "语录6"))
        self.pushButton_p3_25.setText(_translate("MainWindow", "语录10"))
        self.pushButton_p3_26.setText(_translate("MainWindow", "语录7"))
        self.pushButton_p3_27.setText(_translate("MainWindow", "语录8"))
        self.pushButton_p3_28.setText(_translate("MainWindow", "语录9"))
        self.pushButton_p3_29.setText(_translate("MainWindow", "语录11"))
        self.pushButton_p3_30.setText(_translate("MainWindow", "语录12"))
        self.pushButton_p3_31.setText(_translate("MainWindow", "语录13"))
        self.pushButton_p3_32.setText(_translate("MainWindow", "语录14"))
        self.pushButton_p3_33.setText(_translate("MainWindow", "荔枝，拿什么荔枝"))
        self.pushButton_p3_34.setText(_translate("MainWindow", "娱乐圈的规矩"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page3), _translate("MainWindow", "ikun语录"))
        self.pushButton_p4_1.setText(_translate("MainWindow", "暴揍三浦"))
        self.pushButton_p4_2.setText(_translate("MainWindow", "暴揍美国人"))
        self.pushButton_p4_3.setText(_translate("MainWindow", "暴揍雷神"))
        self.pushButton_p4_4.setText(_translate("MainWindow", "暴揍灭霸"))
        self.pushButton_p4_5.setText(_translate("MainWindow", "终鸡杀人王"))
        self.pushButton_p4_6.setText(_translate("MainWindow", "鸡元甲"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "鸡问"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
from .img_rc import *
